### ISSUE TITLE
升级到1.0.3后，CALLBACK_CODE_USER_TYPE_CHANGED用什么消息代替

### ISSUE THREAD

**Issue by uncleciba** [xindong/anti-addiction-kit#10]
升级到1.0.3后，CALLBACK_CODE_USER_TYPE_CHANGED用什么消息代替
我用得Unity

**Comment by horizon554** [comment]
untiy可以升级到1.0.4

**Comment by Leovany** [comment]
> untiy可以升级到1.0.4

为什么没有IOS 1.0.4 版本....

**Comment by uncleciba** [comment]
刚刚升级了，还没运行，不过感觉有点问题哈：
java里：
  public static final int CALLBACK_CODE_USER_TYPE_CHANGED = 1500;
C#里：
CALLBACK_CODE_USER_TYPE_CHANGED,
枚举没赋值，不是1500

**Comment by horizon554** [comment]
是1500，代码遗漏了，可以先手动补上
