### ISSUE TITLE
如何登出？

### ISSUE THREAD

**Issue by liu0fanyi** [xindong/anti-addiction-kit#15]
1.在手册里看到的login和logout两个接口，实际使用发现都显示没定义
login我大概知道是用setUser
logout怎么操作？

2.登陆的时候setuser的id没有限制么？任何字符都可以么？

**Comment by liu0fanyi** [comment]
![image](https://user-images.githubusercontent.com/3987452/77526593-ce7afa00-6ec5-11ea-89cb-1f60c376c385.png)
还有这个init的回调，什么条件下能看到？
现在尝试了init和setuser，都没有看到回调的打印

**Comment by lc1006** [comment]
调用接口显示没定义，请问是是ios还是android 。另外 logout接口是当用户在游戏中点击退出账号等情况时调用SDK接口同步信息的。在登录时设置的userId为非空值即可，没有具体要求。对于回调，除了文档中所说明的，其他是没有回调的

**Comment by liu0fanyi** [comment]
> 调用接口显示没定义，请问是是ios还是android 。另外 logout接口是当用户在游戏中点击退出账号等情况时调用SDK接口同步信息的。在登录时设置的userId为非空值即可，没有具体要求。对于回调，除了文档中所说明的，其他是没有回调的

我是在unity里使用，在demo里有setUser的用法，没有login和logout，尝试调用也显示没有定义。
![image](https://user-images.githubusercontent.com/3987452/77532329-a2fd0d00-6ecf-11ea-8416-2ccce99d65e2.png)

这个是demo里的使用
AntiAddiction 没有login和logout的定义

2.回调那里：
![image](https://user-images.githubusercontent.com/3987452/77532355-b4461980-6ecf-11ea-83fa-00da3d3b767e.png)
这个登陆成功并且通过防沉迷限制
我要如何触发？想至少先看到一个回调。。。
setUser的第二个参数设置为4？

**Comment by lc1006** [comment]
请更新到最新版本，旧版的一些问题已修复

**Comment by liu0fanyi** [comment]
> 请更新到最新版本，旧版的一些问题已修复

额，我是前天刚clone的版本。。。

**Comment by liu0fanyi** [comment]
> 请更新到最新版本，旧版的一些问题已修复

我看了一下，你们的AntiAddictionLocal那个文件夹里的unity版本里有login
我用的是AntiAddictionKitUnity里的unitypackage 1.0.3的，那里的demo么有

**Comment by horizon554** [comment]
用release中最新的版本吧，1.0.4

**Comment by liu0fanyi** [comment]
> 用release中最新的版本吧，1.0.4

再问一下，是不是使用一个用户名id登陆后，实名认证，这个id就跟这个实名绑定了
以后只要用这个id登陆就认为实名过了

**Comment by liu0fanyi** [comment]
> 用release中最新的版本吧，1.0.4

还有就是我依然拿不到回调
![image](https://user-images.githubusercontent.com/3987452/77612579-7a265780-6f63-11ea-8e71-433263a3ba9b.png)
这三个条件应该都达成过
![image](https://user-images.githubusercontent.com/3987452/77612599-87dbdd00-6f63-11ea-9cc3-6e318c318b76.png)
这个demo里回调的打印还是看不到

我有什么办法进一步在这个路径上打印看一下是啥问题么

**Comment by fengwangzi** [comment]
能不能加个好友？有不懂的能问你不？反正都要加这个功能。
