### ISSUE TITLE
有程序员QQ号吗？把DEMO放进项目出包报错阿。

### ISSUE THREAD

**Issue by fengwangzi** [xindong/anti-addiction-kit#16]
Assets\Scripts\AntiAddiction.cs(86,9): error CS0119: 'AndroidJavaClass' is a type, which is not valid in the given context

说明写的不够细致

**Comment by fengwangzi** [comment]
DEMO放到场景中，生成了按钮，按了什么反应都没有啊。

**Comment by liu0fanyi** [comment]
> DEMO放到场景中，生成了按钮，按了什么反应都没有啊。

用release里的版本，clone下来的unitypackage是1.0.3的，就是有错误的，我在隔壁遇到的问题你应该都会遇到。。。

**Comment by fengwangzi** [comment]
这位大侠是做什么游戏的？公司还是个人，能否加个好友。

**Comment by fengwangzi** [comment]
> > DEMO放到场景中，生成了按钮，按了什么反应都没有啊。
> 
> 用release里的版本，clone下来的unitypackage是1.0.3的，就是有错误的，我在隔壁遇到的问题你应该都会遇到。。。

这位大侠是做什么游戏的？公司还是个人，能否加个好友。
