### ISSUE TITLE
在回调中打开自定义UI没反应

### ISSUE THREAD

**Issue by Wecica** [xindong/anti-addiction-kit#18]
我在登录触发防沉迷限制的时候，想给玩家一个提示，但是在回调中调用我的UI打开就不行，我直接调用打开是没有问题的。请教一下有没有遇到过类似问题，我这样写是不是不对。
![TIM截图20200326112624](https://user-images.githubusercontent.com/21235832/77607662-0893dc80-6f56-11ea-975e-44d05c06aac8.png)
![TIM截图20200326113135](https://user-images.githubusercontent.com/21235832/77607666-0df12700-6f56-11ea-8a64-db7e9a42c248.png)

**Comment by misare777** [comment]
请先检查回调文件能否调用自定义的ShowUI函数，是否引入了ShouUI的namespace等可能。
如果确认无误，建议多加几个日志打点跟踪请求中断在了哪里，然后进一步排查
