### ISSUE TITLE
与第三方平台的 jar 冲突

### ISSUE THREAD

**Issue by beyonehu** [xindong/anti-addiction-kit#19]
您好我在接入实名制的时候，和穿山甲的SDK发生了冲突。

Program type already present: android.support.v4.app.ActivityCompat$OnRequestPermissionsResultCallback
![image](https://user-images.githubusercontent.com/3908135/77841085-0aada380-71c1-11ea-8c97-9e585d23fe06.png)

**Comment by lc1006** [comment]
您好，因为第三方平台的SDK中已经包含了android的一些支持库，所以在接入当前SDK时就不需要再接入android支持库了，包括 android-support-*,support-core-ui等
