### ISSUE TITLE
每日限额功能

### ISSUE THREAD

**Issue by jwh18960733474** [xindong/anti-addiction-kit#20]
你们的sdk没有每日限额的功能，paySuccess后只update了每月的充值金额，未达到每月限额且超出每日限额时，依然可以支付，没有限制。

**Comment by JinyaX** [comment]
根据政策，只有单笔付费和月总付费限制，没有单日限制。

**Comment by jwh18960733474** [comment]
ok。了解
有个建议，sdk里的弹框跟提示框的文字都是写死的，如果能读取res资源文件来自定义会更方便一点
