### ISSUE TITLE
能否在UNITY编辑器里直接测试？貌似现在必须出包安装才可以正常显示。

### ISSUE THREAD

**Issue by fengwangzi** [xindong/anti-addiction-kit#21]
把AntiAddiction代码里的编辑器限制删了，但是还是没法显示。如果必须出包才能测，那效率也太低了，出包很慢的啊。

**Comment by misare777** [comment]
> 把AntiAddiction代码里的编辑器限制删了，但是还是没法显示。如果必须出包才能测，那效率也太低了，出包很慢的啊。

以安卓为例，有一些方法在unity中无法直接进行调试，例如
AndroidJavaClass jc = new AndroidJavaClass(“”);此类问题是unity本身桥接安卓就有的，sdk无法直接解决。建议参考下其他人的便捷调试方式，例如：https://www.cnblogs.com/ACDIV/p/8159495.html
