### ISSUE TITLE
AntiAddictionKit.framework  不支持 bitcode

### ISSUE THREAD

**Issue by xmourinho** [xindong/anti-addiction-kit#3]
Unity版本中的 AntiAddictionKit.framework 库不支持 bitcode， 会导致接入AntiAddictionKit的Unity工程在编译 iOS 版本时无法使用bitcode特性。
建议重新编译下 AntiAddictionKit.framework 库， 使它能够支持 bitcode。 或者在接入文档上加上“ENABLE_BITCODE" 为 "NO"的设置提示。

**Comment by horizon554** [comment]
谢谢提醒。后续release版本会加入bitcode支持。
开发者可以先由提供的源码和工程自行编译支持Bitcode的framework
