### ISSUE TITLE
能不能取消要求用户输入手机？

### ISSUE THREAD

**Issue by damienlsq** [xindong/anti-addiction-kit#36]
手机应该不应该强制要求输入的吧？有玩家投诉说收集手机号，希望提供方法取消

还有，海外身份证的人有没有处理的办法？

**Comment by Leovany** [comment]
同求 +1

**Comment by misare777** [comment]
> 手机应该不应该强制要求输入的吧？有玩家投诉说收集手机号，希望提供方法取消
> 
> 还有，海外身份证的人有没有处理的办法？

当前版本不支持，我们会考虑是否在后续版本中优化。
