### ISSUE TITLE
SDK内的实名认证，姓名和手机号乱填也能认证成功

### ISSUE THREAD

**Issue by caogtaa** [xindong/anti-addiction-kit#41]
SDK后续版本是否会接公安的实名系统？

**Comment by lc1006** [comment]
在联网模式下，用户信息的认证是通过服务端，所以项目可以在自己的服务端后台进行用户信息的认证

**Comment by caogtaa** [comment]
> 在联网模式下，用户信息的认证是通过服务端，所以项目可以在自己的服务端后台进行用户信息的认证

不大理解这逻辑，我调用SDK的login，SDK自动弹出一个实名认证窗口，这时候认证不应该是SDK帮助完成吗？怎么又变成应用自己后端做实名认证了？
SDK也没有将用户输入的信息透传回给应用啊？

**Comment by lc1006** [comment]
新版的SDK 1.1.0 分为两种处理方式，单机版和联网版（通过设置host区分，具体说明请看文档），SDK弹出实名窗口后，单机模式，SDK 会在本地对用户信息进行简单的校验，联网模式，会将用户信息上传到游戏设置的host所在的后台服务进行校验
