### ISSUE TITLE
防沉迷系统源码

### ISSUE THREAD

**Issue by h1014179971** [xindong/anti-addiction-kit#49]
你好，很感谢你提供的防沉迷sdk，目前出版社需要我们修改某些提示信息，可否提供源码给我，感激不尽。

**Comment by horizon554** [comment]
源码分别在 iOS 和 Android 目录下

**Comment by h1014179971** [comment]
你好，我在android 没有看到源码，还是只有aar包，我想要aar包里class.jar的源码

**Comment by horizon554** [comment]
有java源码的，在这个目录下
<img width="367" alt="image" src="https://user-images.githubusercontent.com/12759507/88281299-ffefbf00-cd19-11ea-9090-ce4baa6f8cdd.png">

**Comment by graham-lemon** [comment]
> 你好，我在android 没有看到源码，还是只有aar包，我想要aar包里class.jar的源码

系在姐个目录嗄： anti-addiction-kit/Android/GameProtection/protectlib/src/main/java/com/antiaddiction/sdk/

**Comment by h1014179971** [comment]
![image](https://user-images.githubusercontent.com/51565334/89973504-1216aa80-dc93-11ea-8293-151ce512159b.png)
