### ISSUE TITLE
实名认证URL

### ISSUE THREAD

**Issue by h1014179971** [xindong/anti-addiction-kit#50]
你好，感谢你提供的源码，请问我看到你代码里实名认证访问的url链接，你是针对哪个url链接做的逻辑处理呢？可否告诉我链接？
![image](https://user-images.githubusercontent.com/51565334/89478916-0f641300-d7c4-11ea-9664-5f99ab07965f.png)

**Comment by jk625x** [comment]
对应接口 /v1/fcm/real_user_info
在 https://github.com/xindong/anti-addiction-kit/blob/master/Server/app/router.js 可以看到
