### ISSUE TITLE
遇到问题 sdk not initial

### ISSUE THREAD

**Issue by pandacatworks** [xindong/anti-addiction-kit#52]
![QQ图片20201009123429](https://user-images.githubusercontent.com/72593038/95546349-f16c9600-0a32-11eb-9a4a-460314b50956.png)
![QQ图片20201009132621](https://user-images.githubusercontent.com/72593038/95546393-09dcb080-0a33-11eb-86ef-5e990c0c91af.png)

**Comment by misare777** [comment]
看上似乎是配置异常导致初始化没有完成。
将gustertime改成guestTime试试能否正常使用
![image](https://user-images.githubusercontent.com/70249418/96233876-40827000-0fcb-11eb-92c6-4b9a05c469b3.png)
