### ISSUE TITLE
IOS启动报错：Reason: image not found

### ISSUE THREAD

**Issue by Leovany** [xindong/anti-addiction-kit#6]
IOS 版本 V 1.0.3

1. 按照文档配置
2. 运行工程，安装到手机，启动报错，提示
`
dyld: Library not loaded: @rpath/AntiAddictionKit.framework/AntiAddictionKit
  Referenced from: /private/var/containers/Bundle/Application/F91618AB-09F1-42BB-B6EB-B3A65C4EDEFE/cafe.app/cafe

Reason: image not found
`
3. 根据百度结果：在【Build Phases】,增加 CopyFile  AntiAddictionKit.framework
https://www.jianshu.com/p/251eba6fea0c
4. 但还是出现上面的问题

请问下,这个是什么问题，该怎么解决？谢谢

**Comment by JinyaX** [comment]
请确保设置 `Xcode` - `General` - `Frameworks, Libraries, and Embedded Content`中的`AntiAddictionKit.framework`为`Embed & Sign`。
