### ISSUE TITLE
IOS实名认证成功后,getUserType返回0

### ISSUE THREAD

**Issue by Leovany** [xindong/anti-addiction-kit#7]
IOS版本 V1.0.3
1. 登陆
` 
int userType = 0;
NSString *userId = @"Test_1";
[AntiAddictionKit login:userId:userType];
`
2.  重启进入游戏，获取 userType 依旧为 0
`NSString *userId = @"Test_1";
NSInteger userType = [AntiAddictionKit getUserType:userId];
NSLog(@"login,userId = %@ , userType = %ld",userId,userType);
`
3. 检查发现，返回1010情况下，userType 依旧等于 0
`
- (void)onAntiAddictionResult:(NSInteger)code :(NSString *)message {
   if(code == 1010){
      // 实名认证成功
        NSString *userId = @"Test_1";
        NSInteger userType = [AntiAddictionKit getUserType:userId];
        NSLog(@"onAntiAddictionResult,userId = %@ , userType = %ld",userId,userType);  
    }
}

`

请问一下，我之前也接了Android版本，只要实名认证成功了（login）, 那userType 就已经改变，哪怕再次调用 login 也不会弹出认证窗，那IOS版本是否还需要做些什么？
（比如，认证成功后，自己手动修改 userType ？？）

**Comment by JinyaX** [comment]
实名后 getUserType 结果未及时更新，除此之外的用户流程是正常的，下次提交将修复。

> IOS版本 V1.0.3
> 
> 1. 登陆
>    ` int userType = 0; NSString *userId = @"Test_1"; [AntiAddictionKit login:userId:userType];`
> 2. 重启进入游戏，获取 userType 依旧为 0
>    `NSString *userId = @"Test_1"; NSInteger userType = [AntiAddictionKit getUserType:userId]; NSLog(@"login,userId = %@ , userType = %ld",userId,userType); `
> 3. 检查发现，返回1010情况下，userType 依旧等于 0
>    `
> 
> * (void)onAntiAddictionResult:(NSInteger)code :(NSString *)message {
>   if(code == 1010){
>   // 实名认证成功
>   NSString *userId = @"Test_1";
>   NSInteger userType = [AntiAddictionKit getUserType:userId];
>   NSLog(@"onAntiAddictionResult,userId = %@ , userType = %ld",userId,userType);
>   }
>   }
> 
> `
> 
> 请问一下，我之前也接了Android版本，只要实名认证成功了（login）, 那userType 就已经改变，哪怕再次调用 login 也不会弹出认证窗，那IOS版本是否还需要做些什么？
> （比如，认证成功后，自己手动修改 userType ？？）

实名后 getUserType 结果未及时更新，除此之外的用户流程是正常的，下次提交将修复。
